### ISSUE TITLE
Allow to customize CSV Export more flexibly

### ISSUE THREAD

**Issue by takayukister** [rocklobster-in/flamingo#3]
CSV Export is provided in the Address Book and Inbound Messages pages. Feature requests often posted in the support forum are:

- [Allow to add custom columns](https://wordpress.org/support/topic/export-meta-data/)
- [Allow to change the order of items](https://wordpress.org/support/topic/export-with-last-contact-order/)

WordPress core's [personal data exporter](https://wordpress.org/support/article/tools-export-personal-data-screen/) might be a good model case for implementation.

**Comment by itpixelz** [comment]
For both suggestions, adding custom columns and sort order by last added, I suggest we should show a form to check/uncheck available columns of meta to export. For this, I think WordPress core's [personal data exporter](https://wordpress.org/support/article/tools-export-personal-data-screen/) might be a helper as function but we will have to show a form for checkboxes and then a submit button to finally export.

**Comment by marsjaninzmarsa** [comment]
I was totally surprised today, seeing as there is literally no sane way to alter default export behavior programmatically - I was hoping for nice filter to add custom rows, but found out that best I could do is to hook before `flamingo_load_inbound_admin` and `die`-override it, duplicating original code. Pretty disappointing in such well-written plugin. 🙂
