### ISSUE TITLE
Add UTF-8 BOM to CSV export to fix MS Excel encoding issues

### ISSUE THREAD

**Issue by powerbuoy** [rocklobster-in/flamingo#73]
After exporting a CSV and opening it in Microsoft Excel the encoding is wrong. ÅÄÖ etc looks scrambled.

Adding BOM apparently fixes this issue.

Would you consider either:

1) Adding BOM by default
2) Adding a `do_action('flamingo_pre_csv')` at the beginning of the CSV file so we can add it ourselves?

Thank you

**Comment by takayukister** [comment]
Flamingo 2.4 adds `flamingo_contact_csv_class` and `flamingo_inbound_csv_class` filter hooks. Using these hooks you can set your own CSV generator class (Flamingo_CSV subclass) and simply implement BOM output.

See also: #3
